# Generated by Django 5.1 on 2024-08-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('LOANPROVIDER', 'Loan Provider'), ('BANKPERSONNNEL', 'Bank Personnel')], default='BANKPERSONNNEL', max_length=50),
        ),
    ]
